// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB_trk6DId_slgwdf7psOqxna0-gce1y4',
    appId: '1:1076798489464:web:cab3c6597568504031fe8d',
    messagingSenderId: '1076798489464',
    projectId: 'baladens-app',
    authDomain: 'baladens-app.firebaseapp.com',
    storageBucket: 'baladens-app.firebasestorage.app',
    measurementId: 'G-TCDLNT0P1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA79OveIEsdK_G6XwG75A-l-Iq4TaJT_jk',
    appId: '1:1076798489464:android:1b3cda1c8f40872931fe8d',
    messagingSenderId: '1076798489464',
    projectId: 'baladens-app',
    storageBucket: 'baladens-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbFNZjNQVfd2K0-JYIoQN7jK0eXYAl1Oo',
    appId: '1:1076798489464:ios:c6c7549db8e4f5c731fe8d',
    messagingSenderId: '1076798489464',
    projectId: 'baladens-app',
    storageBucket: 'baladens-app.firebasestorage.app',
    iosClientId: '1076798489464-7o17bc75eaak6jq41u6busa2k8jra6if.apps.googleusercontent.com',
    iosBundleId: 'com.example.baladensdiploma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB_trk6DId_slgwdf7psOqxna0-gce1y4',
    appId: '1:1076798489464:web:5fb74bcf8a20e40731fe8d',
    messagingSenderId: '1076798489464',
    projectId: 'baladens-app',
    authDomain: 'baladens-app.firebaseapp.com',
    storageBucket: 'baladens-app.firebasestorage.app',
    measurementId: 'G-KMQR39GVSJ',
  );
}
